[zkevm]
name = "ZisK"
protocol_family = "FRI_STARK"
version = "0.14.0"
field = "Goldilocks^3"
hash_size_bits = 256

[[circuits]]
name = "Main"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [3, 38, 24, 6]
opening_points = 3
batch_size = 61
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Rom"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 2
num_columns = [1, 1, 6, 3, 11]
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Mem"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [2, 13, 9, 6]
opening_points = 3
batch_size = 29
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "RomData"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = [2, 6, 9, 6]
opening_points = 3
batch_size = 19
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "InputData"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = [2, 9, 14, 6]
opening_points = 3
batch_size = 27
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "MemAlign"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = [2, 29, 18, 6]
opening_points = 3
batch_size = 59
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "MemAlignByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 16, 12, 6]
opening_points = 3
batch_size = 25
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "MemAlignReadByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 10, 9, 6]
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "MemAlignWriteByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 14, 12, 6]
opening_points = 3
batch_size = 23
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Arith"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = [1, 44, 45, 6]
opening_points = 3
batch_size = 64
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Binary"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 39, 15, 6]
opening_points = 3
batch_size = 49
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "BinaryAdd"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 10, 9, 6]
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "BinaryExtension"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = [1, 29, 18, 6]
opening_points = 3
batch_size = 40
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Add256"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [1, 47, 51, 6]
opening_points = 3
batch_size = 69
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "ArithEq"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [2, 39, 40, 6]
opening_points = 36
batch_size = 434
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "ArithEq384"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [2, 33, 40, 6]
opening_points = 54
batch_size = 536
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Keccakf"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = [11, 47, 33, 6]
opening_points = 71
batch_size = 265
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Sha256f"
group = "basic"
trace_length = 262144
rho = 0.5
air_max_degree = 3
num_columns = [2, 102, 13, 6]
opening_points = 87
batch_size = 1265
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "SpecifiedRanges"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [34, 33, 51, 6]
opening_points = 3
batch_size = 88
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "VirtualTable0"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [109, 17, 27, 6]
opening_points = 3
batch_size = 139
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "VirtualTable1"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = [145, 16, 27, 6]
opening_points = 3
batch_size = 174
power_batching = true
num_queries = 128
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "ArithEq-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "ArithEq384-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Keccakf-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Sha256f-compressor"
group = "compression"
trace_length = 524288
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 16]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "VirtualTable0-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "VirtualTable1-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = [45, 36, 48, 12]
opening_points = 4
batch_size = 163
power_batching = true
num_queries = 64
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Recursive2"
group = "aggregation"
trace_length = 131072
rho = 0.125
air_max_degree = 8
num_columns = [45, 36, 12, 21]
opening_points = 4
batch_size = 136
power_batching = true
num_queries = 43
fri_folding_factors = [16, 16, 16, 8]
fri_early_stop_degree = 32
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0

[[circuits]]
name = "Final"
group = "final"
trace_length = 65536
rho = 0.0625
air_max_degree = 8
num_columns = [45, 42, 12, 21]
opening_points = 4
batch_size = 142
power_batching = true
num_queries = 32
fri_folding_factors = [32, 32]
fri_early_stop_degree = 1024
grinding_query_phase = 0
merkle_tree_arity = 3
last_level_verification = 0
